modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/JamCoreModding/RightClickHarvest/issues"

[[mods]]
modId = "rightclickharvest"
version = "${file.jarVersion}"
displayName = "Right Click Harvest"
displayURL = "https://github.com/JamCoreModding/RightClickHarvest"
logoFile = "icon.png"
authors = "Jamalam & Various Contributors"
description = '''
Allows you to harvest crops with a single right click.
'''

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
# The version range of the dependency
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"
